print("Hello World")
print("My favorite color is red.")
print("I like to take walks, and enjoy observing wildlife form a distance.")
print("My favorite pastime is drawing.")
print("Welcome to my world")