print("Hello World")
print("My favorite color is red")
print("Welcome to my world")
print("This is my first lab")
print("It is amazing how far technology has come:\"I am excited to see more progress in the future. ")